spring.datasource.url=jdbc:postgresql://localhost:5432/hospital-queue
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
